# Required
# The final name of your plugin, other plugins may use this name to declare dependency on your plugin
name: UnsafeBlocks

# Required
# The name of your class file that overrides PluginBase
main: org.powernukkit.plugins.unsafeblocks.UnsafeBlocksPlugin

# Required
# The version of your plugin, it's recommended to follow the https://semver.org/ standard
version: "1.0.0"

# Required
# The minimum Cloudburst Nukkit API version, it's not the PowerNukkit version!
# Setting an outdated version usually don't cause issues so it's not a thing to worry too much 
api: ["1.0.11"]

# Optional
# At which time your plugin will load.
# Valid options are: POSTWORLD, STARTUP
# Default value is POSTWORLD
load: STARTUP

# Optional
# Your name or your organization name or how people identify you
authors: [joserobjr, good777LUCKY]

# Optional
# Explain in few words what this plugin does
description: Example plugin showing the API

# Optional
# A link where the admins can find more info about your plugin
website: https://github.com/PowerNukkit/UnsafeBlocksPlugin

# Optional
# A list of plugins that are required to use this plugin
# You should keep the PowerNukkit in the list if your plugin requires PowerNukkit features to work properly
depend:
  - PowerNukkit

# Optional
# A list of plugins that should be loaded before, if your plugin works fine with PowerNukkit, keep it in this list
softdepend:
  - PowerNukkit
